### ISSUE TITLE
How move cursor like human?

### ISSUE THREAD

**Issue by Luciener** [evilC/AutoHotInterception#106]
Hello.
The mouse cursor movement is too direct. Is it possible to somehow make the movements more rounded and uneven, so that it looks like human control?
(Window 10, AHK V2, AHI V2)
Screenshot with the lines of movement AHI is attached.
https://imgur.com/gallery/x5IwEfQ

`
#SingleInstance force
Persistent
#Requires AutoHotkey v2.0
#include Lib\AutoHotInterception.ahk

AHI := AutoHotInterception()
MouseID := AHI.GetMouseId(0x02DA, 0x009A , 1)
	Sleep 3000

AHI.MoveCursor(500, 300, ,MouseID)
	Sleep 1000

AHI.SendMouseButtonEvent(MouseID, 0, 1)
	Sleep 1000

AHI.MoveCursor(600, 700, ,MouseID)
	Sleep 1000
AHI.MoveCursor(300, 300, ,MouseID)
	Sleep 1000

AHI.SendMouseButtonEvent(MouseID, 0, 0)
ExitApp
`

**Comment by evilC** [comment]
Yeah, `MoveCursor` is a pretty rudimentary implementation (You can see the code [here](https://github.com/evilC/AutoHotInterception/blob/master/AHK%20v1/Lib/AutoHotInterception.ahk#L96))  
In order to move it more directly, you would need more complex code.  
Because mouse movement is using integers only (No decimals allowed), it would not be trivial to code, so I did not bother, and it's not something that I plan on implementing
