### ISSUE TITLE
Unable to find AutoHotInterception.dll

### ISSUE THREAD

**Issue by kassimir** [evilC/AutoHotInterception#80]
I've tried cloning the repo, and I've tried downloading the folder. I've followed the instructions of downloading the Francisco Lopez interceptor and building it to the best of my ability and grabbing the interceptor.dll files from the x64 and the x86 folders and putting them in the respective lib folders. But when I run Monitor.ahk, I get

`Unable to find D:\AHK\AHI\Lib\AutoHotInterception.ahk\..\AutoHotInterception.dll, exiting...` And it's not wrong. That doesn't exist. Could you tell me how to solve this please?

**Comment by evilC** [comment]
You need to download AHI from the [Releases Page](https://github.com/evilC/AutoHotInterception/releases)

**Comment by OSsqirat** [comment]
Fix Unable to find AutoHotInterception.dll

Just download it from an older version on the Release Page and put it in the Lib folder... and it should work... I believe The new version forgot to add that folder.

I formatted my pc and downloaded the newer version to this date and it did the same issue because in the newer version the "AutoHotInterception.dll" in not included in the lib folder for some reason... 

once you add it from a previous version to the newest version ... it should be running good.

![Make sure to Add this dll from previous folder-2024_02_24_18_48_47_Window](https://github.com/evilC/AutoHotInterception/assets/132025491/07567289-4972-4a81-979c-2f7f18d5f0db)

**Comment by brenidette** [comment]
Have the latest release been fixed yet?
