### ISSUE TITLE
Keyboard randomly stops working

### ISSUE THREAD

**Issue by goddamn-manchild** [evilC/AutoHotInterception#91]
I have got three keyboards plugged into my laptop:

- the native keyboard that is physically inside there.
- a cheap asus keyboard that i'm using to write this on.
- a numeric keyboard where all my scripts are located.

the cheap asus keyboard randomly stops working and only gets back to normal if I: go to devmgmt.msc and uninstall the device from the keyboards list; unplug it and plug it again and also restart w10.

I am wondering if this is some kind of autohotinterception bug

**Comment by evilC** [comment]
Unlikely to be an AHI bug, quite possibly it's a bug in interception.
One thing to check:
Start the AHI monitor, check the ID of the asus keyboard
Wait for the problem to happen, then open the AHI monitor again and check the ID of the asus keyboard again

If the ID of the asus keyboard has changed, this is the root cause of the problem. Interception does not deal well with devices disconnecting and re-connecting
